### ISSUE TITLE
"Drop Excess Inputs" repeated clicks shouldn't extend debounce

### ISSUE THREAD

**Issue by gonX** [Kuuuube/Tablet_Debounce#1]
I get some occasional missed intentional clicks. If there was a way to allow the user to toggle the reset behavior it'd be nice.

Haven't tested it, but it "should" be as simple as just not resetting the stopwatch on a positive pressure change, ie. wrapping [Tablet_Debounce.cs:49](https://github.com/Kuuuube/Tablet_Debounce/blob/main/Tablet_Debounce/Tablet_Debounce.cs#L49) in an `if` statement (with a user exposed option), or outright deleting it.

**Comment by Kuuuube** [comment]
Added in [0.1.1](https://github.com/Kuuuube/Tablet_Debounce/releases/tag/0.1.1). Should be available from the plugin repo soon.
